import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import Navbar from "@/app/components/Navbar";
import {Layout, Flex} from 'antd'
import Sidebar from "@/app/components/Sidebar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(
  {children}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body style={{height: "100vh"}} className={inter.className}>
        <AntdRegistry>
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
